[workspace]
members = [
  "crates/typstlab",
  "crates/typstlab-core",
  "crates/typstlab-lsp/tree-sitter-typstlabtypst",
  "crates/typstlab-lsp/typstlab-lsp-core",
  "crates/typstlab-lsp/typstlab-lsp-macros",
  "crates/typstlab-lsp/typstlab-lsp-server",
  "crates/typstlab-lsp/typstlab-typst-ast",
  "crates/typstlab-lsp/typstlab-typst-parser",
  "crates/typstlab-mcp",
  "crates/typstlab-shim",
  "crates/typstlab-testkit",
  "crates/typstlab-typst",
  "crates/typstlab-watch",
  "xtask",
]

resolver = "2"

[workspace.dependencies]
rmcp = { version = "0.14.0", features = [
  "server",
  "macros",
  "transport-io",
  "schemars",
] }
rmcp-macros = "0.14.0"
tree-sitter = "0.26.3"
