[workspace]
members = [
  "crates/typstlab",
  "crates/typstlab-core",
  "crates/typstlab-typst",
  "crates/typstlab-watch",
  "crates/typstlab-mcp",
  "crates/typstlab-shim",
  "crates/typstlab-testkit",
]

resolver = "2"

[workspace.dependencies]
rmcp = { version = "0.14.0", features = [
  "server",
  "macros",
  "transport-io",
  "schemars",
] }
rmcp-macros = "0.14.0"
