[package]
name = "typstlab-testkit"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3"
tar = "0.4"
xz2 = "0.1"
flate2 = "1.0"
mockito = "1.5"
lazy_static = "1.4"

[target.'cfg(windows)'.dependencies]
zip = "0.6"

[dev-dependencies]
assert_cmd = "2"
