[alias]
xtask = "run --package xtask --"
xtask-tree-sitter-setup = "xtask tree-sitter setup"
xtask-tree-sitter-gen = "xtask tree-sitter generate"
xtask-tree-sitter-verify = "xtask tree-sitter verify"
xtask-tree-sitter-test = "xtask tree-sitter test"
